# Generated by Django 4.2.6 on 2025-10-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandywoods_app', '0003_folder_slug_alter_folder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='slug',
        ),
    ]
